export { default as IcoFooterLogo } from './LogoFooter.svg'
export { default as IcoSearch } from './search.svg'
export { default as IcoDomino } from './domino.svg'
export { default as IcoInstagram } from './instagram.svg'
export { default as IcoTelegram } from './telegram.svg'
export { default as IcoViber } from './viber.svg'
export { default as IcoWhatsapp } from './whatsapp.svg'
export { default as IcoLogo } from './logo.svg'
export { default as IcoBurger } from './burger.svg'
export { default as IcoDoubleArrow } from './double-arrow.svg'

export { default as IcoAppStore } from './app-store.svg'
export { default as IcoGooglePlay } from './google-play.svg'
export { default as IcoMastercard } from './mastercard.svg'
export { default as IcoShopBag } from './Shop bag.svg'
export { default as IcoUccountt } from './uccount.svg'
export { default as IcoVisa } from './visa.svg'
export { default as IcoArrowDown } from './ArrowDown.svg'
