export { default as Service1 } from './services-photo.png'
export { default as ImgDetails } from './details.png'
export { default as ContactFormImg } from './contact-form.jpeg'
export { default as ProductBannerImg } from './banner-bg.png'
export { default as LargeCarImg } from './large-car.png'
export { default as TruckImg } from './truck.png'
export { default as DropdownImg } from './dropdown-image.png'
